/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const EnquireIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path
          fill="#2F88FF"
          stroke="#000"
          strokeMiterlimit={2}
          strokeWidth={4}
          d="M37 16a5 5 0 1 1 0-10 5 5 0 0 1 0 10Zm-25-4a4 4 0 1 1 0-8 4 4 0 0 1 0 8Z"
        />
        <path
          stroke="#000"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          d="m26 39 6-5v-6c0-3.466 2-6 5-6s5 2.534 5 6v14m-18-9-6-5v-4c0-3.466-2-6-5-6s-5 2.534-5 6v18"
        />
      </svg>
    </span>
  );
};

EnquireIcon.propTypes = {
  size: PropTypes.number,
};
export default EnquireIcon;
