/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const FormIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path fill="#fff" fillOpacity={0.01} d="M0 0h48v48H0z" />
        <rect
          width={40}
          height={32}
          x={4}
          y={8}
          fill="#2F88FF"
          stroke="#000"
          strokeLinejoin="round"
          strokeWidth={4}
          rx={2}
        />
        <path fill="#2F88FF" fillRule="evenodd" d="M4 29h40H4Z" clipRule="evenodd" />
        <path stroke="#fff" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M4 29h40" />
        <path fill="#2F88FF" fillRule="evenodd" d="M4 19h40H4Z" clipRule="evenodd" />
        <path stroke="#fff" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M4 19h40" />
        <path fill="#2F88FF" fillRule="evenodd" d="M17 40V19v21Z" clipRule="evenodd" />
        <path stroke="#fff" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M17 40V19" />
        <path fill="#2F88FF" fillRule="evenodd" d="M4 38V17v21Z" clipRule="evenodd" />
        <path stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M4 38V17" />
        <path fill="#2F88FF" fillRule="evenodd" d="M44 38V17v21Z" clipRule="evenodd" />
        <path stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M44 38V17" />
        <path fill="#2F88FF" fillRule="evenodd" d="M31 40V19v21Z" clipRule="evenodd" />
        <path stroke="#fff" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M31 40V19" />
        <path stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M9 40h30" />
      </svg>
    </span>
  );
};

FormIcon.propTypes = {
  size: PropTypes.number,
};
export default FormIcon;
