/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const HandheldIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        fill="currentColor"
        {...props}
      >
        <g fill="none" fillRule="evenodd" strokeLinejoin="round">
          <path fill="#fff" fillOpacity={0.01} d="M0 0h48v48H0z" />
          <path stroke="#000" strokeLinecap="round" strokeWidth={4} d="M42 18v26H6V18h0" />
          <path fill="#2F88FF" fillRule="nonzero" stroke="#000" strokeWidth={4} d="M6 4h36v14H6z" />
          <path stroke="#000" strokeLinecap="round" strokeWidth={4} d="M16 27v8m-4-4h8" />
          <circle cx={32} cy={31} r={4} fill="#2F88FF" fillRule="nonzero" stroke="#000" strokeWidth={4} />
        </g>
      </svg>
    </span>
  );
};

HandheldIcon.propTypes = {
  size: PropTypes.number,
};
export default HandheldIcon;
