/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const HddIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <rect
          width={30}
          height={40}
          x={9}
          y={4}
          fill="#2F88FF"
          stroke="#000"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          rx={2}
        />
        <circle cx={32} cy={10} r={2} fill="#fff" />
        <circle cx={16} cy={10} r={2} fill="#fff" />
        <circle cx={32} cy={38} r={2} fill="#fff" />
        <circle cx={16} cy={38} r={2} fill="#fff" />
        <path
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          d="M24 30a8 8 0 1 0-8-8m8 0-6 6"
        />
      </svg>
    </span>
  );
};

HddIcon.propTypes = {
  size: PropTypes.number,
};
export default HddIcon;
