/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const HeadsetOneIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path fill="#fff" fillOpacity={0.01} d="M0 0h48v48H0z" />
        <path fill="#2F88FF" d="M36 32a8 8 0 1 0 0-16" />
        <path stroke="#000" strokeLinejoin="round" strokeWidth={4} d="M36 32a8 8 0 1 0 0-16" />
        <path fill="#2F88FF" d="M12 16a8 8 0 1 0 0 16" />
        <path stroke="#000" strokeLinejoin="round" strokeWidth={4} d="M12 16a8 8 0 1 0 0 16" />
        <path
          stroke="#000"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          d="M12 32V16c0-6.627 5.373-12 12-12s12 5.373 12 12v16c0 6.627-5.373 12-12 12"
        />
      </svg>
    </span>
  );
};

HeadsetOneIcon.propTypes = {
  size: PropTypes.number,
};
export default HeadsetOneIcon;
