/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const JuiceIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path
          fill="#2F88FF"
          stroke="#000"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          d="M15 24h18l-1.8 20H16.8L15 24Z"
        />
        <rect width={26} height={6} x={11} y={18} stroke="#000" strokeWidth={4} rx={3} />
        <path
          fill="#2F88FF"
          stroke="#000"
          strokeWidth={4}
          d="M24 8c-5.523 0-10 4.477-10 10h20c0-5.523-4.477-10-10-10Z"
        />
        <path stroke="#000" strokeLinecap="round" strokeWidth={4} d="m28 4-2 4" />
      </svg>
    </span>
  );
};

JuiceIcon.propTypes = {
  size: PropTypes.number,
};
export default JuiceIcon;
