/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const ListOneIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path
          fill="#2F88FF"
          stroke="#000"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          d="M18 6h16v6H18V6Zm0 15h20v6H18v-6Zm0 15h26v6H18v-6Z"
        />
        <circle cx={8} cy={9} r={2} fill="#2F88FF" stroke="#000" strokeWidth={4} />
        <circle cx={8} cy={24} r={2} fill="#2F88FF" stroke="#000" strokeWidth={4} />
        <circle cx={8} cy={39} r={2} fill="#2F88FF" stroke="#000" strokeWidth={4} />
      </svg>
    </span>
  );
};

ListOneIcon.propTypes = {
  size: PropTypes.number,
};
export default ListOneIcon;
