/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const OptimizeIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path
          fill="#2F88FF"
          stroke="#000"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          d="m19 8 9 8 10.032-5.89L33 21l9 8-12-1-4.5 10L23 27l-12-1 10.508-6.35L19 8Z"
        />
        <path stroke="#000" strokeLinecap="round" strokeWidth={4} d="M8 42.02 23 27" />
      </svg>
    </span>
  );
};

OptimizeIcon.propTypes = {
  size: PropTypes.number,
};
export default OptimizeIcon;
