/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const OrangeOneIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <g strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} clipPath="url(#prefix__a)">
          <path
            fill="#2F88FF"
            stroke="#000"
            d="M34.15 34.85c8.202-8.202 8.202-21.498 0-29.7L4.453 34.85c8.201 8.2 21.498 8.2 29.699 0Z"
          />
          <path stroke="#fff" d="m19.301 20 14.85 14.85M19.302 20v21.213m0-21.213 20.506.707" />
          <path
            stroke="#000"
            d="M39.755 14.997c1.664 6.88-.189 14.437-5.56 19.809-5.372 5.371-12.93 7.224-19.809 5.56m-.034-15.416 8.485-8.485"
          />
        </g>
        <defs>
          <clipPath id="prefix__a">
            <path fill="#fff" d="M0 0h48v48H0z" />
          </clipPath>
        </defs>
      </svg>
    </span>
  );
};

OrangeOneIcon.propTypes = {
  size: PropTypes.number,
};
export default OrangeOneIcon;
