/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const PearlOfTheOrientIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <circle cx={24} cy={33} r={6} fill="#2F88FF" stroke="#000" strokeWidth={4} />
        <circle cx={24} cy={13} r={3} fill="#2F88FF" stroke="#000" strokeWidth={4} />
        <path
          stroke="#000"
          strokeLinecap="round"
          strokeWidth={4}
          d="M24 40v4m-2-28-2 12m6-12 2 12m-9 9-3 7m13-7 3 7M24 4v6"
        />
      </svg>
    </span>
  );
};

PearlOfTheOrientIcon.propTypes = {
  size: PropTypes.number,
};
export default PearlOfTheOrientIcon;
