/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const PrisonIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path
          stroke="#000"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          d="M6 4v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4M6 7h14m7 15H6v22h21m-11 0V13m-6 9v-9m3-9v3m14 6v3m8-3v3m8-3v3"
        />
        <path
          fill="#2F88FF"
          stroke="#000"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          d="M43 44V16H27v28h16Z"
        />
        <path stroke="#fff" strokeLinecap="round" strokeWidth={4} d="M35 34v10" />
        <path stroke="#000" strokeLinecap="round" strokeWidth={4} d="M31 44h8" />
      </svg>
    </span>
  );
};

PrisonIcon.propTypes = {
  size: PropTypes.number,
};
export default PrisonIcon;
