/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const PumpkinIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <rect width={40} height={26} x={4} y={14} fill="#2F88FF" stroke="#000" strokeWidth={4} rx={13} />
        <ellipse cx={24} cy={27} stroke="#000" strokeWidth={4} rx={8} ry={13} />
        <path stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M30 6h-3a3 3 0 0 0-3 3v5" />
      </svg>
    </span>
  );
};

PumpkinIcon.propTypes = {
  size: PropTypes.number,
};
export default PumpkinIcon;
