/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const ShoppingCartIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path fill="#fff" fillOpacity={0.01} d="M0 0h48v48H0z" />
        <path fill="#2F88FF" d="M39 32H13L8 12h36l-5 20Z" />
        <path
          stroke="#000"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          d="M3 6h3.5L8 12m0 0 5 20h26l5-20H8Z"
        />
        <circle cx={13} cy={39} r={3} stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} />
        <circle cx={39} cy={39} r={3} stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} />
        <path stroke="#fff" strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M22 22h8m-4 4v-8" />
      </svg>
    </span>
  );
};

ShoppingCartIcon.propTypes = {
  size: PropTypes.number,
};
export default ShoppingCartIcon;
