/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const ThemeIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        fill="currentColor"
        {...props}
      >
        <g fill="none" fillRule="evenodd" strokeLinejoin="round">
          <path fill="#fff" fillOpacity={0.01} d="M0 0h48v48H0z" />
          <path
            fill="#2F88FF"
            fillRule="nonzero"
            stroke="#000"
            strokeWidth={4}
            d="M18 6a6 6 0 1 0 12 0h5.455L42 15.818l-5.727 4.91V42H11.727V20.727L6 15.818 12.545 6H18Z"
          />
        </g>
      </svg>
    </span>
  );
};

ThemeIcon.propTypes = {
  size: PropTypes.number,
};
export default ThemeIcon;
