/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const TicketOneIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path
          fill="#2F88FF"
          stroke="#000"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={4}
          d="M4 8h7s1 5 6 5 6-5 6-5h21v32H23s-1-5-6-5-6 5-6 5H4V8Z"
        />
        <path stroke="#fff" strokeLinecap="round" strokeWidth={4} d="M17 19v2m0 6v2m8-8h11m-11 6h11" />
      </svg>
    </span>
  );
};

TicketOneIcon.propTypes = {
  size: PropTypes.number,
};
export default TicketOneIcon;
