/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const TwoDimensionalCodeTwoIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path
          fill="#2F88FF"
          stroke="#000"
          strokeLinejoin="round"
          strokeWidth={4}
          d="M18 6H6v12h12V6Zm0 24H6v12h12V30ZM42 6H30v12h12V6Z"
        />
        <path stroke="#000" strokeLinecap="round" strokeWidth={4} d="M24 6v12m18 6H6m28 6v12m8-12v12M26 30v12" />
      </svg>
    </span>
  );
};

TwoDimensionalCodeTwoIcon.propTypes = {
  size: PropTypes.number,
};
export default TwoDimensionalCodeTwoIcon;
