/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const WaterfallsVIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        fill="currentColor"
        {...props}
      >
        <g fill="none" fillRule="evenodd" strokeLinejoin="round">
          <path fill="#fff" fillOpacity={0.01} d="M0 0h48v48H0z" />
          <path
            fill="#2F88FF"
            fillRule="nonzero"
            stroke="#000"
            strokeWidth={4}
            d="M23 6v14H6V6zm19 22v14H25V28zm-11-8V6h11v14zM6 42V28h11v14z"
          />
        </g>
      </svg>
    </span>
  );
};

WaterfallsVIcon.propTypes = {
  size: PropTypes.number,
};
export default WaterfallsVIcon;
