/**
 * These code auto generated by UltraIcon
 */

/** @jsx jsx */
import { jsx } from '@emotion/react';
import { SVGProps } from 'react';
import PropTypes from 'prop-types';
import iconStyle from '../styles';
import merge from '../utils/merge';
interface SVGComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}
const defaultProps = {
  size: 24,
};

const WindowsIcon = (p: SVGComponentProps) => {
  const { size, ...props } = merge(defaultProps, p);
  return (
    <span css={iconStyle} className="ultra-icon">
      <svg
        fill="currentColor"
        viewBox="0 0 48 48"
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        {...props}
      >
        <path fill="#fff" fillOpacity={0.01} d="M0 0h48v48H0z" />
        <path
          fill="#2F88FF"
          stroke="#000"
          strokeLinejoin="round"
          strokeWidth={3.833}
          d="m6.75 11.063 12.938-1.726v12.076H6.75v-10.35Zm18.113-2.218L41.25 6.75v14.663H24.863V8.845Zm0 18.605 16.387.383V41.25l-16.387-2.683V27.45ZM6.75 26.587l12.938.312V37.8L6.75 35.62v-9.032Z"
        />
      </svg>
    </span>
  );
};

WindowsIcon.propTypes = {
  size: PropTypes.number,
};
export default WindowsIcon;
